kind: Service
apiVersion: v1
metadata:
  name: minikube-sample
spec:
  selector:
    app: minikube-sample
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-sample
spec:
  selector:
    matchLabels:
      app: minikube-sample
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-sample
    spec:
      containers:
        - name: minikube-sample
          image: logranda/minikube-sample
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: minikube-sample
              mountPath: /config
      volumes:
        - name: minikube-sample
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: minikube-sample
            items:
              - key: "application.yaml"
                path: "application.yaml"
