kind: Service
apiVersion: v1
metadata:
  name: minikube-sample
spec:
  selector:
    app: minikube-sample
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-sample
  namespace: default
spec:
  selector:
      matchLabels:
        app: minikube-sample
  replicas: 3
  template:
    metadata:
      labels:
        app: minikube-sample
    spec:
      containers:
        - name: minikube-sample
          image: logranda/minikube-sample
          ports:
            - containerPort: 8080
          env:
            - name: env.namespace
              value: default
          volumeMounts:
          - name: minikube-sample 
            mountPath: /config
            readOnly: true
      volumes:
      - name: minikube-sample
        configMap:
          name: minikube-sample 
          items:
          - key: application.yml 
            path: application.yml
